const OBJECT_COUNT = 10;

const MIN_TITLE_LENGTH = 30;
const MAX_TITLE_LENGTH = 100;

const DATA_SERVER_GET = 'https://23.javascript.pages.academy/keksobooking/data';
const DATA_SERVER_SEND = 'https://23.javascript.pages.academy/keksobooking';

const MAIN_TOKIO_COORDINATS_LAT = 35.67950;
const MAIN_TOKIO_COORDINATS_LNG = 139.72971;
const ZOOM = 13;
const ICON_SIZE_BIG_WIDTH = 52;
const ICON_SIZE_BIG_HEIGHT = 52;
const ICON_SIZE_WIDTH = 40;
const ICON_SIZE_HEIGHT = 40;
const ERROR_TIME = 5000;

const RERENDER_DELAY = 500;
const LOW_PRICE = 10000;
const HIGH_PRICE = 50000;
const ANY_VALUE = 'any';

export {OBJECT_COUNT, DATA_SERVER_GET, DATA_SERVER_SEND, MIN_TITLE_LENGTH, MAX_TITLE_LENGTH, MAIN_TOKIO_COORDINATS_LAT, MAIN_TOKIO_COORDINATS_LNG, ZOOM,ICON_SIZE_BIG_WIDTH, ICON_SIZE_BIG_HEIGHT, ICON_SIZE_WIDTH, ICON_SIZE_HEIGHT, ERROR_TIME,RERENDER_DELAY, LOW_PRICE, HIGH_PRICE, ANY_VALUE};
